// @generated by protoc-gen-connect-es v1.6.1
// @generated from file account.proto (package account, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAccountByGamenameAndTaglineRequest, GetAccountByGamenameAndTaglineResponse, GetAccountByPuuidRequest, GetAccountByPuuidResponse, GetAccountProfileIconRequest, GetAccountProfileIconResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service account.AccountService
 */
export declare const AccountService: {
  readonly typeName: "account.AccountService",
  readonly methods: {
    /**
     * @generated from rpc account.AccountService.GetAccountByGamenameAndTagline
     */
    readonly getAccountByGamenameAndTagline: {
      readonly name: "GetAccountByGamenameAndTagline",
      readonly I: typeof GetAccountByGamenameAndTaglineRequest,
      readonly O: typeof GetAccountByGamenameAndTaglineResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc account.AccountService.GetAccountProfileIcon
     */
    readonly getAccountProfileIcon: {
      readonly name: "GetAccountProfileIcon",
      readonly I: typeof GetAccountProfileIconRequest,
      readonly O: typeof GetAccountProfileIconResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc account.AccountService.GetAccountByPuuid
     */
    readonly getAccountByPuuid: {
      readonly name: "GetAccountByPuuid",
      readonly I: typeof GetAccountByPuuidRequest,
      readonly O: typeof GetAccountByPuuidResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

