// @generated by protoc-gen-es v1.10.0
// @generated from file account.proto (package account, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum account.RegionalRoutingValues
 */
export declare enum RegionalRoutingValues {
  /**
   * @generated from enum value: EUROPE = 0;
   */
  EUROPE = 0,

  /**
   * @generated from enum value: AMERICAS = 1;
   */
  AMERICAS = 1,

  /**
   * @generated from enum value: ASIA = 2;
   */
  ASIA = 2,

  /**
   * @generated from enum value: ESPORTS = 3;
   */
  ESPORTS = 3,
}

/**
 * @generated from message account.GetAccountByGamenameAndTaglineRequest
 */
export declare class GetAccountByGamenameAndTaglineRequest extends Message<GetAccountByGamenameAndTaglineRequest> {
  /**
   * @generated from field: string gamename = 1;
   */
  gamename: string;

  /**
   * @generated from field: string tagline = 2;
   */
  tagline: string;

  /**
   * @generated from field: account.RegionalRoutingValues region = 3;
   */
  region: RegionalRoutingValues;

  constructor(data?: PartialMessage<GetAccountByGamenameAndTaglineRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountByGamenameAndTaglineRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByGamenameAndTaglineRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByGamenameAndTaglineRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByGamenameAndTaglineRequest;

  static equals(a: GetAccountByGamenameAndTaglineRequest | PlainMessage<GetAccountByGamenameAndTaglineRequest> | undefined, b: GetAccountByGamenameAndTaglineRequest | PlainMessage<GetAccountByGamenameAndTaglineRequest> | undefined): boolean;
}

/**
 * @generated from message account.Account
 */
export declare class Account extends Message<Account> {
  /**
   * @generated from field: string puuid = 1;
   */
  puuid: string;

  /**
   * @generated from field: string gameName = 2;
   */
  gameName: string;

  /**
   * @generated from field: string tagLine = 3;
   */
  tagLine: string;

  constructor(data?: PartialMessage<Account>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.Account";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account;

  static equals(a: Account | PlainMessage<Account> | undefined, b: Account | PlainMessage<Account> | undefined): boolean;
}

/**
 * @generated from message account.GetAccountByGamenameAndTaglineResponse
 */
export declare class GetAccountByGamenameAndTaglineResponse extends Message<GetAccountByGamenameAndTaglineResponse> {
  /**
   * @generated from field: account.Account account = 1;
   */
  account?: Account;

  constructor(data?: PartialMessage<GetAccountByGamenameAndTaglineResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountByGamenameAndTaglineResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByGamenameAndTaglineResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByGamenameAndTaglineResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByGamenameAndTaglineResponse;

  static equals(a: GetAccountByGamenameAndTaglineResponse | PlainMessage<GetAccountByGamenameAndTaglineResponse> | undefined, b: GetAccountByGamenameAndTaglineResponse | PlainMessage<GetAccountByGamenameAndTaglineResponse> | undefined): boolean;
}

/**
 * @generated from message account.GetAccountProfileIconRequest
 */
export declare class GetAccountProfileIconRequest extends Message<GetAccountProfileIconRequest> {
  /**
   * @generated from field: int32 profileIconId = 1;
   */
  profileIconId: number;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetAccountProfileIconRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountProfileIconRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountProfileIconRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountProfileIconRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountProfileIconRequest;

  static equals(a: GetAccountProfileIconRequest | PlainMessage<GetAccountProfileIconRequest> | undefined, b: GetAccountProfileIconRequest | PlainMessage<GetAccountProfileIconRequest> | undefined): boolean;
}

/**
 * @generated from message account.GetAccountProfileIconResponse
 */
export declare class GetAccountProfileIconResponse extends Message<GetAccountProfileIconResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetAccountProfileIconResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountProfileIconResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountProfileIconResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountProfileIconResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountProfileIconResponse;

  static equals(a: GetAccountProfileIconResponse | PlainMessage<GetAccountProfileIconResponse> | undefined, b: GetAccountProfileIconResponse | PlainMessage<GetAccountProfileIconResponse> | undefined): boolean;
}

/**
 * @generated from message account.GetAccountByPuuidRequest
 */
export declare class GetAccountByPuuidRequest extends Message<GetAccountByPuuidRequest> {
  /**
   * @generated from field: string puuid = 1;
   */
  puuid: string;

  /**
   * @generated from field: account.RegionalRoutingValues region = 2;
   */
  region: RegionalRoutingValues;

  constructor(data?: PartialMessage<GetAccountByPuuidRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountByPuuidRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByPuuidRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByPuuidRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByPuuidRequest;

  static equals(a: GetAccountByPuuidRequest | PlainMessage<GetAccountByPuuidRequest> | undefined, b: GetAccountByPuuidRequest | PlainMessage<GetAccountByPuuidRequest> | undefined): boolean;
}

/**
 * @generated from message account.GetAccountByPuuidResponse
 */
export declare class GetAccountByPuuidResponse extends Message<GetAccountByPuuidResponse> {
  /**
   * @generated from field: account.Account account = 1;
   */
  account?: Account;

  constructor(data?: PartialMessage<GetAccountByPuuidResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.GetAccountByPuuidResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAccountByPuuidResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAccountByPuuidResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAccountByPuuidResponse;

  static equals(a: GetAccountByPuuidResponse | PlainMessage<GetAccountByPuuidResponse> | undefined, b: GetAccountByPuuidResponse | PlainMessage<GetAccountByPuuidResponse> | undefined): boolean;
}

