// @generated by protoc-gen-es v1.10.0
// @generated from file assets.proto (package assets, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Image } from "./champions_pb.js";

/**
 * @generated from message assets.GetRuneIconRequest
 */
export const GetRuneIconRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetRuneIconRequest",
  () => [
    { no: 1, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "style", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message assets.GetRuneIconResponse
 */
export const GetRuneIconResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetRuneIconResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetSummonerSpellIconRequest
 */
export const GetSummonerSpellIconRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetSummonerSpellIconRequest",
  () => [
    { no: 1, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image", kind: "message", T: Image },
  ],
);

/**
 * @generated from message assets.GetSummonerSpellIconResponse
 */
export const GetSummonerSpellIconResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetSummonerSpellIconResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetItemAssetUrlRequest
 */
export const GetItemAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetItemAssetUrlRequest",
  () => [
    { no: 1, name: "itemName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetItemAssetUrlResponse
 */
export const GetItemAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetItemAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetSpellAssetUrlRequest
 */
export const GetSpellAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetSpellAssetUrlRequest",
  () => [
    { no: 1, name: "spellName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetSpellAssetUrlResponse
 */
export const GetSpellAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetSpellAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionAbilityAssetUrlRequest
 */
export const GetChampionAbilityAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionAbilityAssetUrlRequest",
  () => [
    { no: 1, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "abilityNumber", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionAbilityAssetUrlResponse
 */
export const GetChampionAbilityAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionAbilityAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionPassiveAssetUrlRequest
 */
export const GetChampionPassiveAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionPassiveAssetUrlRequest",
  () => [
    { no: 1, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionPassiveAssetUrlResponse
 */
export const GetChampionPassiveAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionPassiveAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionSquareAssetUrlRequest
 */
export const GetChampionSquareAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionSquareAssetUrlRequest",
  () => [
    { no: 1, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionSquareAssetUrlResponse
 */
export const GetChampionSquareAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionSquareAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionLoadingScreenAssetUrlRequest
 */
export const GetChampionLoadingScreenAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionLoadingScreenAssetUrlRequest",
  () => [
    { no: 1, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "skinNumber", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message assets.GetChampionLoadingScreenAssetUrlResponse
 */
export const GetChampionLoadingScreenAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionLoadingScreenAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message assets.GetChampionSplashAssetUrlRequest
 */
export const GetChampionSplashAssetUrlRequest = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionSplashAssetUrlRequest",
  () => [
    { no: 1, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "skinNumber", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message assets.GetChampionSplashAssetUrlResponse
 */
export const GetChampionSplashAssetUrlResponse = /*@__PURE__*/ proto3.makeMessageType(
  "assets.GetChampionSplashAssetUrlResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

