// @generated by protoc-gen-es v1.10.0
// @generated from file assets.proto (package assets, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Image } from "./champions_pb.js";

/**
 * @generated from message assets.GetRuneIconRequest
 */
export declare class GetRuneIconRequest extends Message<GetRuneIconRequest> {
  /**
   * @generated from field: string patchVersion = 1;
   */
  patchVersion: string;

  /**
   * @generated from field: int32 style = 2;
   */
  style: number;

  constructor(data?: PartialMessage<GetRuneIconRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetRuneIconRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRuneIconRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRuneIconRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRuneIconRequest;

  static equals(a: GetRuneIconRequest | PlainMessage<GetRuneIconRequest> | undefined, b: GetRuneIconRequest | PlainMessage<GetRuneIconRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetRuneIconResponse
 */
export declare class GetRuneIconResponse extends Message<GetRuneIconResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetRuneIconResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetRuneIconResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRuneIconResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRuneIconResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRuneIconResponse;

  static equals(a: GetRuneIconResponse | PlainMessage<GetRuneIconResponse> | undefined, b: GetRuneIconResponse | PlainMessage<GetRuneIconResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetSummonerSpellIconRequest
 */
export declare class GetSummonerSpellIconRequest extends Message<GetSummonerSpellIconRequest> {
  /**
   * @generated from field: string patchVersion = 1;
   */
  patchVersion: string;

  /**
   * @generated from field: champions.Image image = 2;
   */
  image?: Image;

  constructor(data?: PartialMessage<GetSummonerSpellIconRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetSummonerSpellIconRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummonerSpellIconRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummonerSpellIconRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummonerSpellIconRequest;

  static equals(a: GetSummonerSpellIconRequest | PlainMessage<GetSummonerSpellIconRequest> | undefined, b: GetSummonerSpellIconRequest | PlainMessage<GetSummonerSpellIconRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetSummonerSpellIconResponse
 */
export declare class GetSummonerSpellIconResponse extends Message<GetSummonerSpellIconResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetSummonerSpellIconResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetSummonerSpellIconResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummonerSpellIconResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummonerSpellIconResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummonerSpellIconResponse;

  static equals(a: GetSummonerSpellIconResponse | PlainMessage<GetSummonerSpellIconResponse> | undefined, b: GetSummonerSpellIconResponse | PlainMessage<GetSummonerSpellIconResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetItemAssetUrlRequest
 */
export declare class GetItemAssetUrlRequest extends Message<GetItemAssetUrlRequest> {
  /**
   * @generated from field: string itemName = 1;
   */
  itemName: string;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetItemAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetItemAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetItemAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetItemAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetItemAssetUrlRequest;

  static equals(a: GetItemAssetUrlRequest | PlainMessage<GetItemAssetUrlRequest> | undefined, b: GetItemAssetUrlRequest | PlainMessage<GetItemAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetItemAssetUrlResponse
 */
export declare class GetItemAssetUrlResponse extends Message<GetItemAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetItemAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetItemAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetItemAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetItemAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetItemAssetUrlResponse;

  static equals(a: GetItemAssetUrlResponse | PlainMessage<GetItemAssetUrlResponse> | undefined, b: GetItemAssetUrlResponse | PlainMessage<GetItemAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetSpellAssetUrlRequest
 */
export declare class GetSpellAssetUrlRequest extends Message<GetSpellAssetUrlRequest> {
  /**
   * @generated from field: string spellName = 1;
   */
  spellName: string;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetSpellAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetSpellAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSpellAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSpellAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSpellAssetUrlRequest;

  static equals(a: GetSpellAssetUrlRequest | PlainMessage<GetSpellAssetUrlRequest> | undefined, b: GetSpellAssetUrlRequest | PlainMessage<GetSpellAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetSpellAssetUrlResponse
 */
export declare class GetSpellAssetUrlResponse extends Message<GetSpellAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetSpellAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetSpellAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSpellAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSpellAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSpellAssetUrlResponse;

  static equals(a: GetSpellAssetUrlResponse | PlainMessage<GetSpellAssetUrlResponse> | undefined, b: GetSpellAssetUrlResponse | PlainMessage<GetSpellAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionAbilityAssetUrlRequest
 */
export declare class GetChampionAbilityAssetUrlRequest extends Message<GetChampionAbilityAssetUrlRequest> {
  /**
   * @generated from field: string championName = 1;
   */
  championName: string;

  /**
   * @generated from field: int32 abilityNumber = 2;
   */
  abilityNumber: number;

  /**
   * @generated from field: string patchVersion = 3;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetChampionAbilityAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionAbilityAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionAbilityAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionAbilityAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionAbilityAssetUrlRequest;

  static equals(a: GetChampionAbilityAssetUrlRequest | PlainMessage<GetChampionAbilityAssetUrlRequest> | undefined, b: GetChampionAbilityAssetUrlRequest | PlainMessage<GetChampionAbilityAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionAbilityAssetUrlResponse
 */
export declare class GetChampionAbilityAssetUrlResponse extends Message<GetChampionAbilityAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetChampionAbilityAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionAbilityAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionAbilityAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionAbilityAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionAbilityAssetUrlResponse;

  static equals(a: GetChampionAbilityAssetUrlResponse | PlainMessage<GetChampionAbilityAssetUrlResponse> | undefined, b: GetChampionAbilityAssetUrlResponse | PlainMessage<GetChampionAbilityAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionPassiveAssetUrlRequest
 */
export declare class GetChampionPassiveAssetUrlRequest extends Message<GetChampionPassiveAssetUrlRequest> {
  /**
   * @generated from field: string championName = 1;
   */
  championName: string;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetChampionPassiveAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionPassiveAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionPassiveAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionPassiveAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionPassiveAssetUrlRequest;

  static equals(a: GetChampionPassiveAssetUrlRequest | PlainMessage<GetChampionPassiveAssetUrlRequest> | undefined, b: GetChampionPassiveAssetUrlRequest | PlainMessage<GetChampionPassiveAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionPassiveAssetUrlResponse
 */
export declare class GetChampionPassiveAssetUrlResponse extends Message<GetChampionPassiveAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetChampionPassiveAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionPassiveAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionPassiveAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionPassiveAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionPassiveAssetUrlResponse;

  static equals(a: GetChampionPassiveAssetUrlResponse | PlainMessage<GetChampionPassiveAssetUrlResponse> | undefined, b: GetChampionPassiveAssetUrlResponse | PlainMessage<GetChampionPassiveAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionSquareAssetUrlRequest
 */
export declare class GetChampionSquareAssetUrlRequest extends Message<GetChampionSquareAssetUrlRequest> {
  /**
   * @generated from field: string championName = 1;
   */
  championName: string;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetChampionSquareAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionSquareAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionSquareAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionSquareAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionSquareAssetUrlRequest;

  static equals(a: GetChampionSquareAssetUrlRequest | PlainMessage<GetChampionSquareAssetUrlRequest> | undefined, b: GetChampionSquareAssetUrlRequest | PlainMessage<GetChampionSquareAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionSquareAssetUrlResponse
 */
export declare class GetChampionSquareAssetUrlResponse extends Message<GetChampionSquareAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetChampionSquareAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionSquareAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionSquareAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionSquareAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionSquareAssetUrlResponse;

  static equals(a: GetChampionSquareAssetUrlResponse | PlainMessage<GetChampionSquareAssetUrlResponse> | undefined, b: GetChampionSquareAssetUrlResponse | PlainMessage<GetChampionSquareAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionLoadingScreenAssetUrlRequest
 */
export declare class GetChampionLoadingScreenAssetUrlRequest extends Message<GetChampionLoadingScreenAssetUrlRequest> {
  /**
   * @generated from field: string championName = 1;
   */
  championName: string;

  /**
   * @generated from field: int32 skinNumber = 2;
   */
  skinNumber: number;

  constructor(data?: PartialMessage<GetChampionLoadingScreenAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionLoadingScreenAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionLoadingScreenAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionLoadingScreenAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionLoadingScreenAssetUrlRequest;

  static equals(a: GetChampionLoadingScreenAssetUrlRequest | PlainMessage<GetChampionLoadingScreenAssetUrlRequest> | undefined, b: GetChampionLoadingScreenAssetUrlRequest | PlainMessage<GetChampionLoadingScreenAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionLoadingScreenAssetUrlResponse
 */
export declare class GetChampionLoadingScreenAssetUrlResponse extends Message<GetChampionLoadingScreenAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetChampionLoadingScreenAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionLoadingScreenAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionLoadingScreenAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionLoadingScreenAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionLoadingScreenAssetUrlResponse;

  static equals(a: GetChampionLoadingScreenAssetUrlResponse | PlainMessage<GetChampionLoadingScreenAssetUrlResponse> | undefined, b: GetChampionLoadingScreenAssetUrlResponse | PlainMessage<GetChampionLoadingScreenAssetUrlResponse> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionSplashAssetUrlRequest
 */
export declare class GetChampionSplashAssetUrlRequest extends Message<GetChampionSplashAssetUrlRequest> {
  /**
   * @generated from field: string championName = 1;
   */
  championName: string;

  /**
   * @generated from field: int32 skinNumber = 2;
   */
  skinNumber: number;

  constructor(data?: PartialMessage<GetChampionSplashAssetUrlRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionSplashAssetUrlRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionSplashAssetUrlRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionSplashAssetUrlRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionSplashAssetUrlRequest;

  static equals(a: GetChampionSplashAssetUrlRequest | PlainMessage<GetChampionSplashAssetUrlRequest> | undefined, b: GetChampionSplashAssetUrlRequest | PlainMessage<GetChampionSplashAssetUrlRequest> | undefined): boolean;
}

/**
 * @generated from message assets.GetChampionSplashAssetUrlResponse
 */
export declare class GetChampionSplashAssetUrlResponse extends Message<GetChampionSplashAssetUrlResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetChampionSplashAssetUrlResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "assets.GetChampionSplashAssetUrlResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChampionSplashAssetUrlResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChampionSplashAssetUrlResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChampionSplashAssetUrlResponse;

  static equals(a: GetChampionSplashAssetUrlResponse | PlainMessage<GetChampionSplashAssetUrlResponse> | undefined, b: GetChampionSplashAssetUrlResponse | PlainMessage<GetChampionSplashAssetUrlResponse> | undefined): boolean;
}

