// @generated by protoc-gen-connect-es v1.6.1
// @generated from file assets.proto (package assets, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetChampionAbilityAssetUrlRequest, GetChampionAbilityAssetUrlResponse, GetChampionLoadingScreenAssetUrlRequest, GetChampionLoadingScreenAssetUrlResponse, GetChampionPassiveAssetUrlRequest, GetChampionPassiveAssetUrlResponse, GetChampionSplashAssetUrlRequest, GetChampionSplashAssetUrlResponse, GetChampionSquareAssetUrlRequest, GetChampionSquareAssetUrlResponse, GetItemAssetUrlRequest, GetItemAssetUrlResponse, GetRuneIconRequest, GetRuneIconResponse, GetSpellAssetUrlRequest, GetSpellAssetUrlResponse, GetSummonerSpellIconRequest, GetSummonerSpellIconResponse } from "./assets_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service assets.AssetsService
 */
export declare const AssetsService: {
  readonly typeName: "assets.AssetsService",
  readonly methods: {
    /**
     * @generated from rpc assets.AssetsService.GetRuneIcon
     */
    readonly getRuneIcon: {
      readonly name: "GetRuneIcon",
      readonly I: typeof GetRuneIconRequest,
      readonly O: typeof GetRuneIconResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetSummonerSpellIcon
     */
    readonly getSummonerSpellIcon: {
      readonly name: "GetSummonerSpellIcon",
      readonly I: typeof GetSummonerSpellIconRequest,
      readonly O: typeof GetSummonerSpellIconResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetItemAssetUrl
     */
    readonly getItemAssetUrl: {
      readonly name: "GetItemAssetUrl",
      readonly I: typeof GetItemAssetUrlRequest,
      readonly O: typeof GetItemAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetSpellAssetUrl
     */
    readonly getSpellAssetUrl: {
      readonly name: "GetSpellAssetUrl",
      readonly I: typeof GetSpellAssetUrlRequest,
      readonly O: typeof GetSpellAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionAbilityAssetUrl
     */
    readonly getChampionAbilityAssetUrl: {
      readonly name: "GetChampionAbilityAssetUrl",
      readonly I: typeof GetChampionAbilityAssetUrlRequest,
      readonly O: typeof GetChampionAbilityAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionPassiveAssetUrl
     */
    readonly getChampionPassiveAssetUrl: {
      readonly name: "GetChampionPassiveAssetUrl",
      readonly I: typeof GetChampionPassiveAssetUrlRequest,
      readonly O: typeof GetChampionPassiveAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionSquareAssetUrl
     */
    readonly getChampionSquareAssetUrl: {
      readonly name: "GetChampionSquareAssetUrl",
      readonly I: typeof GetChampionSquareAssetUrlRequest,
      readonly O: typeof GetChampionSquareAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionLoadingScreenAssetUrl
     */
    readonly getChampionLoadingScreenAssetUrl: {
      readonly name: "GetChampionLoadingScreenAssetUrl",
      readonly I: typeof GetChampionLoadingScreenAssetUrlRequest,
      readonly O: typeof GetChampionLoadingScreenAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionSplashAssetUrl
     */
    readonly getChampionSplashAssetUrl: {
      readonly name: "GetChampionSplashAssetUrl",
      readonly I: typeof GetChampionSplashAssetUrlRequest,
      readonly O: typeof GetChampionSplashAssetUrlResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

