// @generated by protoc-gen-connect-es v1.6.1
// @generated from file assets.proto (package assets, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetChampionAbilityAssetUrlRequest, GetChampionAbilityAssetUrlResponse, GetChampionLoadingScreenAssetUrlRequest, GetChampionLoadingScreenAssetUrlResponse, GetChampionPassiveAssetUrlRequest, GetChampionPassiveAssetUrlResponse, GetChampionSplashAssetUrlRequest, GetChampionSplashAssetUrlResponse, GetChampionSquareAssetUrlRequest, GetChampionSquareAssetUrlResponse, GetItemAssetUrlRequest, GetItemAssetUrlResponse, GetRuneIconRequest, GetRuneIconResponse, GetSpellAssetUrlRequest, GetSpellAssetUrlResponse, GetSummonerSpellIconRequest, GetSummonerSpellIconResponse } from "./assets_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service assets.AssetsService
 */
export const AssetsService = {
  typeName: "assets.AssetsService",
  methods: {
    /**
     * @generated from rpc assets.AssetsService.GetRuneIcon
     */
    getRuneIcon: {
      name: "GetRuneIcon",
      I: GetRuneIconRequest,
      O: GetRuneIconResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetSummonerSpellIcon
     */
    getSummonerSpellIcon: {
      name: "GetSummonerSpellIcon",
      I: GetSummonerSpellIconRequest,
      O: GetSummonerSpellIconResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetItemAssetUrl
     */
    getItemAssetUrl: {
      name: "GetItemAssetUrl",
      I: GetItemAssetUrlRequest,
      O: GetItemAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetSpellAssetUrl
     */
    getSpellAssetUrl: {
      name: "GetSpellAssetUrl",
      I: GetSpellAssetUrlRequest,
      O: GetSpellAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionAbilityAssetUrl
     */
    getChampionAbilityAssetUrl: {
      name: "GetChampionAbilityAssetUrl",
      I: GetChampionAbilityAssetUrlRequest,
      O: GetChampionAbilityAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionPassiveAssetUrl
     */
    getChampionPassiveAssetUrl: {
      name: "GetChampionPassiveAssetUrl",
      I: GetChampionPassiveAssetUrlRequest,
      O: GetChampionPassiveAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionSquareAssetUrl
     */
    getChampionSquareAssetUrl: {
      name: "GetChampionSquareAssetUrl",
      I: GetChampionSquareAssetUrlRequest,
      O: GetChampionSquareAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionLoadingScreenAssetUrl
     */
    getChampionLoadingScreenAssetUrl: {
      name: "GetChampionLoadingScreenAssetUrl",
      I: GetChampionLoadingScreenAssetUrlRequest,
      O: GetChampionLoadingScreenAssetUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc assets.AssetsService.GetChampionSplashAssetUrl
     */
    getChampionSplashAssetUrl: {
      name: "GetChampionSplashAssetUrl",
      I: GetChampionSplashAssetUrlRequest,
      O: GetChampionSplashAssetUrlResponse,
      kind: MethodKind.Unary,
    },
  }
};

