// @generated by protoc-gen-connect-es v1.6.1
// @generated from file champions.proto (package champions, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetChampionsRequest, GetChampionsResponse } from "./champions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service champions.ChampionsService
 */
export const ChampionsService = {
  typeName: "champions.ChampionsService",
  methods: {
    /**
     * @generated from rpc champions.ChampionsService.GetChampions
     */
    getChampions: {
      name: "GetChampions",
      I: GetChampionsRequest,
      O: GetChampionsResponse,
      kind: MethodKind.Unary,
    },
  }
};

