// @generated by protoc-gen-es v1.10.0
// @generated from file entries.proto (package entries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { PlatformRoutingValues } from "./summoner_pb.js";

/**
 * @generated from message entries.GetEntriesBySummonerRequest
 */
export const GetEntriesBySummonerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "entries.GetEntriesBySummonerRequest",
  () => [
    { no: 1, name: "region", kind: "enum", T: proto3.getEnumType(PlatformRoutingValues) },
    { no: 2, name: "summonerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message entries.GetEntriesBySummonerResponse
 */
export const GetEntriesBySummonerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "entries.GetEntriesBySummonerResponse",
  () => [
    { no: 1, name: "entries", kind: "message", T: SummonerEntry, repeated: true },
  ],
);

/**
 * @generated from message entries.SummonerEntry
 */
export const SummonerEntry = /*@__PURE__*/ proto3.makeMessageType(
  "entries.SummonerEntry",
  () => [
    { no: 1, name: "leagueId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "queueId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "rank", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "summonerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "leaguePoints", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "wins", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "losses", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "veteran", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "inactive", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "freshBlood", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "hotStreak", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

