// @generated by protoc-gen-connect-es v1.6.1
// @generated from file entries.proto (package entries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetEntriesBySummonerRequest, GetEntriesBySummonerResponse } from "./entries_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service entries.EntriesService
 */
export declare const EntriesService: {
  readonly typeName: "entries.EntriesService",
  readonly methods: {
    /**
     * @generated from rpc entries.EntriesService.GetEntriesBySummoner
     */
    readonly getEntriesBySummoner: {
      readonly name: "GetEntriesBySummoner",
      readonly I: typeof GetEntriesBySummonerRequest,
      readonly O: typeof GetEntriesBySummonerResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

