// @generated by protoc-gen-connect-es v1.6.1
// @generated from file entries.proto (package entries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetEntriesBySummonerRequest, GetEntriesBySummonerResponse } from "./entries_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service entries.EntriesService
 */
export const EntriesService = {
  typeName: "entries.EntriesService",
  methods: {
    /**
     * @generated from rpc entries.EntriesService.GetEntriesBySummoner
     */
    getEntriesBySummoner: {
      name: "GetEntriesBySummoner",
      I: GetEntriesBySummonerRequest,
      O: GetEntriesBySummonerResponse,
      kind: MethodKind.Unary,
    },
  }
};

