// @generated by protoc-gen-es v1.10.0
// @generated from file entries.proto (package entries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { PlatformRoutingValues } from "./summoner_pb.js";

/**
 * @generated from message entries.GetEntriesBySummonerRequest
 */
export declare class GetEntriesBySummonerRequest extends Message<GetEntriesBySummonerRequest> {
  /**
   * @generated from field: summoner.PlatformRoutingValues region = 1;
   */
  region: PlatformRoutingValues;

  /**
   * @generated from field: string summonerId = 2;
   */
  summonerId: string;

  constructor(data?: PartialMessage<GetEntriesBySummonerRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "entries.GetEntriesBySummonerRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEntriesBySummonerRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEntriesBySummonerRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEntriesBySummonerRequest;

  static equals(a: GetEntriesBySummonerRequest | PlainMessage<GetEntriesBySummonerRequest> | undefined, b: GetEntriesBySummonerRequest | PlainMessage<GetEntriesBySummonerRequest> | undefined): boolean;
}

/**
 * @generated from message entries.GetEntriesBySummonerResponse
 */
export declare class GetEntriesBySummonerResponse extends Message<GetEntriesBySummonerResponse> {
  /**
   * @generated from field: repeated entries.SummonerEntry entries = 1;
   */
  entries: SummonerEntry[];

  constructor(data?: PartialMessage<GetEntriesBySummonerResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "entries.GetEntriesBySummonerResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEntriesBySummonerResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEntriesBySummonerResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEntriesBySummonerResponse;

  static equals(a: GetEntriesBySummonerResponse | PlainMessage<GetEntriesBySummonerResponse> | undefined, b: GetEntriesBySummonerResponse | PlainMessage<GetEntriesBySummonerResponse> | undefined): boolean;
}

/**
 * @generated from message entries.SummonerEntry
 */
export declare class SummonerEntry extends Message<SummonerEntry> {
  /**
   * @generated from field: string leagueId = 1;
   */
  leagueId: string;

  /**
   * @generated from field: string queueId = 2;
   */
  queueId: string;

  /**
   * @generated from field: string tier = 3;
   */
  tier: string;

  /**
   * @generated from field: string rank = 4;
   */
  rank: string;

  /**
   * @generated from field: string summonerId = 5;
   */
  summonerId: string;

  /**
   * @generated from field: int32 leaguePoints = 6;
   */
  leaguePoints: number;

  /**
   * @generated from field: int32 wins = 7;
   */
  wins: number;

  /**
   * @generated from field: int32 losses = 8;
   */
  losses: number;

  /**
   * @generated from field: bool veteran = 9;
   */
  veteran: boolean;

  /**
   * @generated from field: bool inactive = 10;
   */
  inactive: boolean;

  /**
   * @generated from field: bool freshBlood = 11;
   */
  freshBlood: boolean;

  /**
   * @generated from field: bool hotStreak = 12;
   */
  hotStreak: boolean;

  constructor(data?: PartialMessage<SummonerEntry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "entries.SummonerEntry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SummonerEntry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SummonerEntry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SummonerEntry;

  static equals(a: SummonerEntry | PlainMessage<SummonerEntry> | undefined, b: SummonerEntry | PlainMessage<SummonerEntry> | undefined): boolean;
}

