// @generated by protoc-gen-connect-es v1.6.1
// @generated from file masteries.proto (package masteries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetChampionMasteriesByChampionRequeset, GetChampionMasteriesByChampionResponse, GetChampionMasteriesRequeset, GetChampionMasteriesResponse } from "./masteries_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service masteries.MasteriesService
 */
export declare const MasteriesService: {
  readonly typeName: "masteries.MasteriesService",
  readonly methods: {
    /**
     * @generated from rpc masteries.MasteriesService.GetChampionMasteriesByPuuid
     */
    readonly getChampionMasteriesByPuuid: {
      readonly name: "GetChampionMasteriesByPuuid",
      readonly I: typeof GetChampionMasteriesRequeset,
      readonly O: typeof GetChampionMasteriesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc masteries.MasteriesService.GetChampionMasteriesByPuuidByChampion
     */
    readonly getChampionMasteriesByPuuidByChampion: {
      readonly name: "GetChampionMasteriesByPuuidByChampion",
      readonly I: typeof GetChampionMasteriesByChampionRequeset,
      readonly O: typeof GetChampionMasteriesByChampionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

