// @generated by protoc-gen-es v1.10.0
// @generated from file masteries.proto (package masteries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { PlatformRoutingValues } from "./summoner_pb.js";

/**
 * @generated from message masteries.GetChampionMasteriesRequeset
 */
export const GetChampionMasteriesRequeset = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.GetChampionMasteriesRequeset",
  () => [
    { no: 1, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "region", kind: "enum", T: proto3.getEnumType(PlatformRoutingValues) },
  ],
);

/**
 * @generated from message masteries.NextSeasonMilestone
 */
export const NextSeasonMilestone = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.NextSeasonMilestone",
  () => [
    { no: 1, name: "rewardMarks", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "bonus", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "totalGamesRequires", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "requireGradeCounts", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 5 /* ScalarType.INT32 */} },
  ],
);

/**
 * @generated from message masteries.ChampionMastery
 */
export const ChampionMastery = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.ChampionMastery",
  () => [
    { no: 1, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "championId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "championLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "championPoints", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "lastPlayTime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "championPointsSinceLastLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "championPointsUntilNextLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "markRequiredForNextLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "tokensEarned", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "championSeasonMilestone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "milestoneGrades", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 12, name: "nextSeasonMilestone", kind: "message", T: NextSeasonMilestone },
  ],
);

/**
 * @generated from message masteries.GetChampionMasteriesResponse
 */
export const GetChampionMasteriesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.GetChampionMasteriesResponse",
  () => [
    { no: 1, name: "championMasteries", kind: "message", T: ChampionMastery, repeated: true },
  ],
);

/**
 * @generated from message masteries.GetChampionMasteriesByChampionRequeset
 */
export const GetChampionMasteriesByChampionRequeset = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.GetChampionMasteriesByChampionRequeset",
  () => [
    { no: 1, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "championId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "region", kind: "enum", T: proto3.getEnumType(PlatformRoutingValues) },
  ],
);

/**
 * @generated from message masteries.GetChampionMasteriesByChampionResponse
 */
export const GetChampionMasteriesByChampionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "masteries.GetChampionMasteriesByChampionResponse",
  () => [
    { no: 1, name: "championMastery", kind: "message", T: ChampionMastery },
  ],
);

