// @generated by protoc-gen-es v1.10.0
// @generated from file matches.proto (package matches, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { RegionalRoutingValues } from "./account_pb.js";

/**
 * @generated from message matches.GetMatchIdsByPuuidRequest
 */
export const GetMatchIdsByPuuidRequest = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchIdsByPuuidRequest",
  () => [
    { no: 1, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "region", kind: "enum", T: proto3.getEnumType(RegionalRoutingValues) },
    { no: 3, name: "startTime", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "endTime", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "queue", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "start", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 8, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message matches.GetMatchIdsByPuuidResponse
 */
export const GetMatchIdsByPuuidResponse = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchIdsByPuuidResponse",
  () => [
    { no: 1, name: "matchIds", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message matches.GetMatchByMatchIdRequest
 */
export const GetMatchByMatchIdRequest = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchByMatchIdRequest",
  () => [
    { no: 1, name: "matchId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "region", kind: "enum", T: proto3.getEnumType(RegionalRoutingValues) },
  ],
);

/**
 * @generated from message matches.GetMatchByMatchIdResponse
 */
export const GetMatchByMatchIdResponse = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchByMatchIdResponse",
  () => [
    { no: 1, name: "match", kind: "message", T: Match },
  ],
);

/**
 * @generated from message matches.MatchMetadata
 */
export const MatchMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "matches.MatchMetadata",
  () => [
    { no: 1, name: "dataVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "matchId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "participants", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message matches.MatchInfo
 */
export const MatchInfo = /*@__PURE__*/ proto3.makeMessageType(
  "matches.MatchInfo",
  () => [
    { no: 1, name: "endOfGameResult", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "gameCreation", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "gameDuration", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "gameEndTimestamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "gameId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "gameMode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "gameName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "gameStartTimestamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "gameType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "gameVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "mapId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "platformId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "queueId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 14, name: "tournamentCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "participants", kind: "message", T: MatchParticipant, repeated: true },
    { no: 16, name: "teams", kind: "message", T: Team, repeated: true },
  ],
);

/**
 * @generated from message matches.Team
 */
export const Team = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Team",
  () => [
    { no: 1, name: "bans", kind: "message", T: Ban, repeated: true },
    { no: 2, name: "objectives", kind: "message", T: Objective, repeated: true },
    { no: 3, name: "teamId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "win", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message matches.Ban
 */
export const Ban = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Ban",
  () => [
    { no: 1, name: "championId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "pickTurn", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Objective
 */
export const Objective = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Objective",
  () => [
    { no: 1, name: "baron", kind: "message", T: ObjectiveTarget },
    { no: 2, name: "champion", kind: "message", T: ObjectiveTarget },
    { no: 3, name: "dragon", kind: "message", T: ObjectiveTarget },
    { no: 4, name: "horde", kind: "message", T: ObjectiveTarget },
    { no: 5, name: "inhibitor", kind: "message", T: ObjectiveTarget },
    { no: 6, name: "riftHerald", kind: "message", T: ObjectiveTarget },
    { no: 7, name: "tower", kind: "message", T: ObjectiveTarget },
  ],
);

/**
 * @generated from message matches.ObjectiveTarget
 */
export const ObjectiveTarget = /*@__PURE__*/ proto3.makeMessageType(
  "matches.ObjectiveTarget",
  () => [
    { no: 1, name: "first", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "kills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.MatchParticipant
 */
export const MatchParticipant = /*@__PURE__*/ proto3.makeMessageType(
  "matches.MatchParticipant",
  () => [
    { no: 1, name: "allInPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "assistMePings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "assists", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "baronKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "basicPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "bountyLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "challanges", kind: "message", T: Challange, repeated: true },
    { no: 8, name: "champExperience", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "champLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "championId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "championName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "championTransform", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "commandPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 14, name: "consumablesPurchased", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "damageDealtToBuildings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 16, name: "damageDealtToObjectives", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 17, name: "damageDealtToTurrets", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 18, name: "damageSelfMitigated", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 19, name: "dangerPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 20, name: "deaths", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 21, name: "detectorWardsPlaced", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 22, name: "doubleKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 23, name: "dragonKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 24, name: "eligibleForProgression", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 25, name: "enemyMissingPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 26, name: "enemyVisionPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 27, name: "firstBloodAssist", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 28, name: "firstBloodKill", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 29, name: "firstTowerAssist", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 30, name: "firstTowerKill", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 31, name: "gameEndedInEarlySurrender", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 32, name: "gameEndedInSurrender", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 33, name: "getBackPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 34, name: "goldEarned", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 35, name: "goldSpent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 36, name: "holdPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 37, name: "individualPosition", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 38, name: "inhibitorKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 39, name: "inhibitorTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 40, name: "inhibitorsLost", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 41, name: "item0", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 42, name: "item1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 43, name: "item2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 44, name: "item3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 45, name: "item4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 46, name: "item5", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 47, name: "item6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 48, name: "itemsPurchased", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 49, name: "killingSprees", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 50, name: "kills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 51, name: "lane", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 52, name: "largestCriticalStrike", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 53, name: "largestKillingSpree", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 54, name: "largestMultiKill", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 55, name: "longestTimeSpentLiving", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 56, name: "magicDamageDealt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 57, name: "magicDamageDealtToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 58, name: "magicDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 59, name: "missions", kind: "message", T: Mission, repeated: true },
    { no: 60, name: "needVisionPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 61, name: "neutralMinionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 62, name: "nexusKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 63, name: "nexusLost", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 64, name: "nexusTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 65, name: "objectivesStolen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 66, name: "objectivesStolenAssists", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 67, name: "onMyWayPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 68, name: "participantId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 69, name: "pentaKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 70, name: "perks", kind: "message", T: Perk, repeated: true },
    { no: 71, name: "physicalDamageDealt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 72, name: "physicalDamageDealtToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 73, name: "physicalDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 74, name: "placement", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 75, name: "playerAugment1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 76, name: "playerAugment2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 77, name: "playerAugment3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 78, name: "playerAugment4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 79, name: "playerAugment5", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 80, name: "playerAugment6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 81, name: "playerSubteamId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 82, name: "profileIcon", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 83, name: "pushPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 84, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 85, name: "quadraKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 86, name: "riotIdGameName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 87, name: "riotIdTagline", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 88, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 89, name: "sightWardsBoughtInGame", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 90, name: "spell1Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 91, name: "spell2Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 92, name: "spell3Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 93, name: "spell4Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 94, name: "subteamPlacement", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 95, name: "summoner1Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 96, name: "summoner1Id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 97, name: "summoner2Casts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 98, name: "summoner2Id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 99, name: "summonerId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 100, name: "summonerLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 101, name: "summonerName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 102, name: "teamEarlySurrendered", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 103, name: "teamId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 104, name: "teamPosition", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 105, name: "timeCCingOthers", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 106, name: "timePlayed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 107, name: "totalAllyJungleMinionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 108, name: "totalDamageDealt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 109, name: "totalDamageDealtToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 110, name: "totalDamageShieldedOnTeammates", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 111, name: "totalDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 112, name: "totalEnemyJungleMinionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 113, name: "totalHeal", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 114, name: "totalHealsOnTeammates", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 115, name: "totalMinionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 116, name: "totalTimeCCDealt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 117, name: "totalTimeSpentDead", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 118, name: "totalUnitsHealed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 119, name: "tripleKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 120, name: "trueDamageDealt", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 121, name: "trueDamageDealtToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 122, name: "trueDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 123, name: "turretKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 124, name: "turretTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 125, name: "turretsLost", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 126, name: "unrealKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 127, name: "visionClearedPings", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 128, name: "visionScore", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 129, name: "visionWardsBoughtInGame", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 130, name: "wardsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 131, name: "wardsPlaced", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 132, name: "win", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message matches.Perk
 */
export const Perk = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Perk",
  () => [
    { no: 1, name: "statPerks", kind: "message", T: StatPerks },
    { no: 2, name: "stylePerks", kind: "message", T: StylePerks },
  ],
);

/**
 * @generated from message matches.StatPerks
 */
export const StatPerks = /*@__PURE__*/ proto3.makeMessageType(
  "matches.StatPerks",
  () => [
    { no: 1, name: "defense", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "flex", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "offense", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.StylePerks
 */
export const StylePerks = /*@__PURE__*/ proto3.makeMessageType(
  "matches.StylePerks",
  () => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "selections", kind: "message", T: StylePerkSelection, repeated: true },
    { no: 3, name: "style", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.StylePerkSelection
 */
export const StylePerkSelection = /*@__PURE__*/ proto3.makeMessageType(
  "matches.StylePerkSelection",
  () => [
    { no: 1, name: "perk", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "var1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "var2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "var3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Mission
 */
export const Mission = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Mission",
  () => [
    { no: 1, name: "playerScore0", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "playerScore1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "playerScore2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "playerScore3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "playerScore4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "playerScore5", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "playerScore6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "playerScore7", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "playerScore8", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "playerScore9", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "playerScore10", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "playerScore11", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Challange
 */
export const Challange = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Challange",
  () => [
    { no: 2, name: "HealFromMapSources", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "InfernalScalePickups", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "SWARM_DefeatAatrox", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "SWARM_DefeatBriar", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "SWARM_DefeatMiniBosses", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "SWARM_EvolveWeapon", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "SWARM_Have3Passives", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "SWARM_KillEnemy", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "SWARM_PickupGold", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "SWARM_ReachLevel50", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "SWARM_Survive15Min", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "SWARM_WinWith5EvolvedWeapons", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 14, name: "abilityUses", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "acesBefore15Minutes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 16, name: "alliedJungleMonsterKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 17, name: "baronTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 18, name: "blastConeOppositeOpponentCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 19, name: "bountyGold", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 20, name: "buffsStolen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 21, name: "completeSupportQuestInTime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 22, name: "controlWardsPlaced", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 23, name: "damagePerMinute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 24, name: "damageTakenOnTeamPercentage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 25, name: "dancedWithRiftHerald", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 26, name: "deathsByEnemyChamps", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 27, name: "dodgeSkillShotsSmallWindow", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 28, name: "doubleAces", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 29, name: "dragonTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 30, name: "effectiveHealAndShielding", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 31, name: "elderDragonKillsWithOpposingSoul", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 32, name: "elderDragonMultikills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 33, name: "enemyChampionImmobilizations", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 34, name: "enemyJungleMonsterKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 35, name: "epicMonsterKillsNearEnemyJungler", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 36, name: "epicMonsterKillsWithin30SecondsOfSpawn", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 37, name: "epicMonsterSteals", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 38, name: "epicMonsterStolenWithoutSmite", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 39, name: "firstTurretKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 40, name: "fistBumpParticipation", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 41, name: "flawlessAces", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 42, name: "fullTeamTakedown", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 43, name: "gameLength", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 44, name: "getTakedownsInAllLanesEarlyJungleAsLaner", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 45, name: "goldPerMinute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 46, name: "hadOpenNexus", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 47, name: "immobilizeAndKillWithAlly", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 48, name: "initialBuffCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 49, name: "initialCrabCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 50, name: "jungleCsBefore10Minutes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 51, name: "junglerTakedownsNearDamagedEpicMonster", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 52, name: "kTurretsDestroyedBeforePlatesFall", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 53, name: "kda", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 54, name: "killAfterHiddenWithAlly", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 55, name: "killParticipation", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 56, name: "killedChampTookFullTeamDamageSurvived", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 57, name: "killingSprees", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 58, name: "killsNearEnemyTurret", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 59, name: "killsOnOtherLanesEarlyJungleAsLaner", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 60, name: "killsOnRecentlyHealedByAramPack", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 61, name: "killsUnderOwnTurret", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 62, name: "killsWithHelpFromEpicMonster", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 63, name: "knockEnemyIntoTeamAndKill", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 64, name: "landSkillShotsEarlyGame", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 65, name: "laneMinionsFirst10Minutes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 66, name: "legendaryCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 67, name: "legendaryItemUsed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 68, name: "lostAnInhibitor", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 69, name: "maxKillDeficit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 70, name: "mejaisFullStackInTime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 71, name: "moreEnemyJungleThanOpponent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 72, name: "multiKillOneSpell", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 73, name: "multiTurretRiftHeraldCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 74, name: "multikills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 75, name: "multikillsAfterAggressiveFlash", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 76, name: "outerTurretExecutesBefore10Minutes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 77, name: "outnumberedKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 78, name: "outnumberedNexusKill", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 79, name: "perfectDragonSoulsTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 80, name: "perfectGame", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 81, name: "pickKillWithAlly", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 82, name: "poroExplosions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 83, name: "quickCleanse", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 84, name: "quickFirstTurret", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 85, name: "quickSoloKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 86, name: "riftHeraldTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 87, name: "saveAllyFromDeath", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 88, name: "scuttleCrabKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 89, name: "shortestTimeToAceFromFirstTakedown", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 90, name: "skillshotsDodged", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 91, name: "skillshotsHit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 92, name: "snowballsHit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 93, name: "soloBaronKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 94, name: "soloKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 95, name: "stealthWardsPlaced", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 96, name: "survivedSingleDigitHpCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 97, name: "survivedThreeImmobilizesInFight", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 98, name: "takedownOnFirstTurret", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 99, name: "takedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 100, name: "takedownsAfterGainingLevelAdvantage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 101, name: "takedownsBeforeJungleMinionSpawn", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 102, name: "takedownsFirstXMinutes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 103, name: "takedownsInAlcove", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 104, name: "takedownsInEnemyFountain", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 105, name: "teamBaronKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 106, name: "teamDamagePercentage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 107, name: "teamElderDragonKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 108, name: "teamRiftHeraldKills", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 109, name: "tookLargeDamageSurvived", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 110, name: "turretPlatesTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 111, name: "turretTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 112, name: "turretsTakenWithRiftHerald", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 113, name: "twentyMinionsIn3SecondsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 114, name: "twoWardsOneSweeperCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 115, name: "unseenRecalls", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 116, name: "visionScorePerMinute", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 117, name: "voidMonsterKill", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 118, name: "wardTakedowns", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 119, name: "wardTakedownsBefore20M", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 120, name: "wardsGuarded", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Match
 */
export const Match = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Match",
  () => [
    { no: 1, name: "metadata", kind: "message", T: Metadata },
    { no: 2, name: "info", kind: "message", T: MatchInfo },
  ],
);

/**
 * @generated from message matches.GetMatchTimelineRequest
 */
export const GetMatchTimelineRequest = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchTimelineRequest",
  () => [
    { no: 1, name: "matchId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "region", kind: "enum", T: proto3.getEnumType(RegionalRoutingValues) },
  ],
);

/**
 * @generated from message matches.GetMatchTimelineResponse
 */
export const GetMatchTimelineResponse = /*@__PURE__*/ proto3.makeMessageType(
  "matches.GetMatchTimelineResponse",
  () => [
    { no: 1, name: "timeline", kind: "message", T: Timeline },
  ],
);

/**
 * @generated from message matches.Timeline
 */
export const Timeline = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Timeline",
  () => [
    { no: 1, name: "metadata", kind: "message", T: Metadata },
    { no: 2, name: "info", kind: "message", T: Info },
  ],
);

/**
 * @generated from message matches.Metadata
 */
export const Metadata = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Metadata",
  () => [
    { no: 1, name: "dataVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "matchId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "participants", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message matches.Info
 */
export const Info = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Info",
  () => [
    { no: 1, name: "endOfGameResult", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "frameInterval", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "frames", kind: "message", T: Frame, repeated: true },
    { no: 4, name: "gameId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "participants", kind: "message", T: Participant, repeated: true },
  ],
);

/**
 * @generated from message matches.Participant
 */
export const Participant = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Participant",
  () => [
    { no: 1, name: "participantId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message matches.Frame
 */
export const Frame = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Frame",
  () => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "participantFrames", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ParticipantFrame} },
  ],
);

/**
 * @generated from message matches.ParticipantChampionStats
 */
export const ParticipantChampionStats = /*@__PURE__*/ proto3.makeMessageType(
  "matches.ParticipantChampionStats",
  () => [
    { no: 1, name: "abilityHaste", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "abilityPower", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "armor", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "armorPen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "armorPenPercent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "attackDamage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "attackSpeed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "bonusArmorPenPercent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "bonusMagicPenPercent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "ccReduction", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "cooldownReduction", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "health", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "healthMax", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 14, name: "healthRegen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "lifesteal", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 16, name: "magicPen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 17, name: "magicPenPercent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 18, name: "magicResist", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 19, name: "movementSpeed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 20, name: "omnivamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 21, name: "physicalVamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 22, name: "power", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 23, name: "powerMax", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 24, name: "powerRegen", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 25, name: "spellVamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.DamageStats
 */
export const DamageStats = /*@__PURE__*/ proto3.makeMessageType(
  "matches.DamageStats",
  () => [
    { no: 1, name: "magicDamageDone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "magicDamageDoneToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "magicDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "physicalDamageDone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "physicalDamageDoneToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "physicalDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "totalDamageDone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "totalDamageDoneToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "totalDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "trueDamageDone", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "trueDamageDoneToChampions", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "trueDamageTaken", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.ParticipantFrame
 */
export const ParticipantFrame = /*@__PURE__*/ proto3.makeMessageType(
  "matches.ParticipantFrame",
  () => [
    { no: 2, name: "championStats", kind: "message", T: ParticipantChampionStats },
    { no: 3, name: "currentGold", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "damageStats", kind: "message", T: DamageStats },
    { no: 5, name: "goldPerSecond", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "jungleMinionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "minionsKilled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "participantId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "position", kind: "message", T: Position },
    { no: 11, name: "timeEnemySpentControlled", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "totalGold", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "xp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Event
 */
export const Event = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Event",
  () => [
    { no: 1, name: "realTimestamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "levelUpType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "participantId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "skillSlot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "itemId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "creatorId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "wardType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "bounty", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "killStreakLength", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "killerId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 14, name: "position", kind: "message", T: Position },
    { no: 15, name: "shutdownBounty", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 16, name: "victimDamageDealt", kind: "message", T: VictimDamage, repeated: true },
    { no: 17, name: "victimDamageReceived", kind: "message", T: VictimDamage, repeated: true },
    { no: 18, name: "victimId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 19, name: "killType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "assistingParticipantIds", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 21, name: "afterId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 22, name: "beforeId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 23, name: "goldGain", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 24, name: "killerTeamId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 25, name: "monsterType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 26, name: "monsterSubType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 27, name: "laneType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 28, name: "teamId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 29, name: "buildingType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 30, name: "towerType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 31, name: "multiKillLength", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 32, name: "actualStartTime", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 33, name: "gameId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 34, name: "winningTeam", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.Position
 */
export const Position = /*@__PURE__*/ proto3.makeMessageType(
  "matches.Position",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "y", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message matches.VictimDamage
 */
export const VictimDamage = /*@__PURE__*/ proto3.makeMessageType(
  "matches.VictimDamage",
  () => [
    { no: 1, name: "basic", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "magicDamage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "participantId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "physicalDamage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "spellName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "spellSlot", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "trueDamage", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

