// @generated by protoc-gen-connect-es v1.6.1
// @generated from file matches.proto (package matches, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMatchByMatchIdRequest, GetMatchByMatchIdResponse, GetMatchIdsByPuuidRequest, GetMatchIdsByPuuidResponse, GetMatchTimelineRequest, GetMatchTimelineResponse } from "./matches_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service matches.MatchesService
 */
export const MatchesService = {
  typeName: "matches.MatchesService",
  methods: {
    /**
     * @generated from rpc matches.MatchesService.GetMatchTimeline
     */
    getMatchTimeline: {
      name: "GetMatchTimeline",
      I: GetMatchTimelineRequest,
      O: GetMatchTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc matches.MatchesService.GetMatchByMatchId
     */
    getMatchByMatchId: {
      name: "GetMatchByMatchId",
      I: GetMatchByMatchIdRequest,
      O: GetMatchByMatchIdResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc matches.MatchesService.GetMatchIdsByPuuid
     */
    getMatchIdsByPuuid: {
      name: "GetMatchIdsByPuuid",
      I: GetMatchIdsByPuuidRequest,
      O: GetMatchIdsByPuuidResponse,
      kind: MethodKind.Unary,
    },
  }
};

