// @generated by protoc-gen-es v1.10.0
// @generated from file summoner.proto (package summoner, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Image } from "./champions_pb.js";

/**
 * @generated from enum summoner.PlatformRoutingValues
 */
export const PlatformRoutingValues = /*@__PURE__*/ proto3.makeEnum(
  "summoner.PlatformRoutingValues",
  [
    {no: 0, name: "BR1"},
    {no: 1, name: "EUN1"},
    {no: 2, name: "EUW1"},
    {no: 3, name: "JP1"},
    {no: 4, name: "KR"},
    {no: 5, name: "LA1"},
    {no: 6, name: "LA2"},
    {no: 7, name: "ME1"},
    {no: 8, name: "NA1"},
    {no: 9, name: "OC1"},
    {no: 10, name: "PH1"},
    {no: 11, name: "RU"},
    {no: 12, name: "SG2"},
    {no: 13, name: "TH2"},
    {no: 14, name: "TR1"},
    {no: 15, name: "TW2"},
    {no: 16, name: "VN2"},
  ],
);

/**
 * @generated from message summoner.GetSummonerByPuuidRequest
 */
export const GetSummonerByPuuidRequest = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.GetSummonerByPuuidRequest",
  () => [
    { no: 1, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "region", kind: "enum", T: proto3.getEnumType(PlatformRoutingValues) },
  ],
);

/**
 * @generated from message summoner.GetSummonerByPuuidResponse
 */
export const GetSummonerByPuuidResponse = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.GetSummonerByPuuidResponse",
  () => [
    { no: 1, name: "summoner", kind: "message", T: Summoner },
  ],
);

/**
 * @generated from message summoner.Summoner
 */
export const Summoner = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.Summoner",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "accountId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "puuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "profileIconId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "revisionDate", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "summonerLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message summoner.GetSummonerSpellsRequest
 */
export const GetSummonerSpellsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.GetSummonerSpellsRequest",
  () => [
    { no: 1, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message summoner.GetSummonerSpellsResponse
 */
export const GetSummonerSpellsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.GetSummonerSpellsResponse",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: SummonerSpell} },
  ],
);

/**
 * @generated from message summoner.SummonerSpell
 */
export const SummonerSpell = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.SummonerSpell",
  () => [
    { no: 1, name: "cooldown", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 2, name: "cooldownBurn", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cost", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 4, name: "costBurn", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "costType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "datavalues", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 7, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "effect", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 9, name: "effectBurn", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "image", kind: "message", T: Image },
    { no: 12, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "maxammo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "maxrank", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 15, name: "modes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 16, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "range", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 18, name: "rangeBurn", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 19, name: "resource", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "summonerLevel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 21, name: "tooltip", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "vars", kind: "message", T: SummonerSpellVar, repeated: true },
  ],
);

/**
 * @generated from message summoner.SummonerSpellVar
 */
export const SummonerSpellVar = /*@__PURE__*/ proto3.makeMessageType(
  "summoner.SummonerSpellVar",
  () => [
    { no: 1, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "coeff", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

