// @generated by protoc-gen-connect-es v1.6.1
// @generated from file summoner.proto (package summoner, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSummonerByPuuidRequest, GetSummonerByPuuidResponse, GetSummonerSpellsRequest, GetSummonerSpellsResponse } from "./summoner_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service summoner.SummonerService
 */
export const SummonerService = {
  typeName: "summoner.SummonerService",
  methods: {
    /**
     * @generated from rpc summoner.SummonerService.GetSummonerByPuuid
     */
    getSummonerByPuuid: {
      name: "GetSummonerByPuuid",
      I: GetSummonerByPuuidRequest,
      O: GetSummonerByPuuidResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc summoner.SummonerService.GetSummonerSpells
     */
    getSummonerSpells: {
      name: "GetSummonerSpells",
      I: GetSummonerSpellsRequest,
      O: GetSummonerSpellsResponse,
      kind: MethodKind.Unary,
    },
  }
};

