// @generated by protoc-gen-connect-es v1.6.1
// @generated from file summoner.proto (package summoner, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSummonerByPuuidRequest, GetSummonerByPuuidResponse, GetSummonerSpellsRequest, GetSummonerSpellsResponse } from "./summoner_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service summoner.SummonerService
 */
export declare const SummonerService: {
  readonly typeName: "summoner.SummonerService",
  readonly methods: {
    /**
     * @generated from rpc summoner.SummonerService.GetSummonerByPuuid
     */
    readonly getSummonerByPuuid: {
      readonly name: "GetSummonerByPuuid",
      readonly I: typeof GetSummonerByPuuidRequest,
      readonly O: typeof GetSummonerByPuuidResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc summoner.SummonerService.GetSummonerSpells
     */
    readonly getSummonerSpells: {
      readonly name: "GetSummonerSpells",
      readonly I: typeof GetSummonerSpellsRequest,
      readonly O: typeof GetSummonerSpellsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

