// @generated by protoc-gen-es v1.10.0
// @generated from file tier.proto (package tier, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tier.GetTierIconRequest
 */
export declare class GetTierIconRequest extends Message<GetTierIconRequest> {
  /**
   * @generated from field: string tier = 1;
   */
  tier: string;

  /**
   * @generated from field: string patchVersion = 2;
   */
  patchVersion: string;

  constructor(data?: PartialMessage<GetTierIconRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tier.GetTierIconRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTierIconRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTierIconRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTierIconRequest;

  static equals(a: GetTierIconRequest | PlainMessage<GetTierIconRequest> | undefined, b: GetTierIconRequest | PlainMessage<GetTierIconRequest> | undefined): boolean;
}

/**
 * @generated from message tier.GetTierIconResponse
 */
export declare class GetTierIconResponse extends Message<GetTierIconResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  constructor(data?: PartialMessage<GetTierIconResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "tier.GetTierIconResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTierIconResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTierIconResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTierIconResponse;

  static equals(a: GetTierIconResponse | PlainMessage<GetTierIconResponse> | undefined, b: GetTierIconResponse | PlainMessage<GetTierIconResponse> | undefined): boolean;
}

