// @generated by protoc-gen-es v1.10.0
// @generated from file tier.proto (package tier, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message tier.GetTierIconRequest
 */
export const GetTierIconRequest = /*@__PURE__*/ proto3.makeMessageType(
  "tier.GetTierIconRequest",
  () => [
    { no: 1, name: "tier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message tier.GetTierIconResponse
 */
export const GetTierIconResponse = /*@__PURE__*/ proto3.makeMessageType(
  "tier.GetTierIconResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

