// @generated by protoc-gen-connect-es v1.6.1
// @generated from file tier.proto (package tier, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTierIconRequest, GetTierIconResponse } from "./tier_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service tier.TierService
 */
export const TierService = {
  typeName: "tier.TierService",
  methods: {
    /**
     * @generated from rpc tier.TierService.GetTierIcon
     */
    getTierIcon: {
      name: "GetTierIcon",
      I: GetTierIconRequest,
      O: GetTierIconResponse,
      kind: MethodKind.Unary,
    },
  }
};

