// @generated by protoc-gen-es v1.10.0
// @generated from file version.proto (package version, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message version.GetVersionsRequest
 */
export const GetVersionsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "version.GetVersionsRequest",
  [],
);

/**
 * @generated from message version.GetVersionsResponse
 */
export const GetVersionsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "version.GetVersionsResponse",
  () => [
    { no: 1, name: "versions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

